### PR TITLE
Added gemma.pdf (Gemma M0 starting guide)

### PR DESCRIPTION
**Pull request by ewjoachim**
Source is https://docs.google.com/document/d/16C8kjnd8WPzDrhzyz6TgibrWVn-manTgeDespB3mEmA/edit

Original document is https://cdn-learn.adafruit.com/assets/assets/000/053/672/original/PyCon_Gemma_M0_Quickstart.pdf?1526074477

Ping @jbbqq

### CODE REVIEW

**Comment by ewjoachim** [comment]
@jbbqq New commit, with your corrections

**Comment by liZe** [comment]
Can I merge?

**Comment by ewjoachim** [comment]
From my point of view, yes, but maybe @jbbqq 's opinion on the matter is more valuable :)

**Comment by jbbqqf** [comment]
Pas de contre-indication :)

**Comment by ewjoachim** [comment]
Let’s :shipit:

**Pull request merged**
